# Generated by Django 4.2.5 on 2023-10-03 13:02

import backEnd.react_front_end.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile-picture')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[backEnd.react_front_end.models.phone_regex_validator])),
            ],
        ),
    ]
