# Generated by Django 4.2.5 on 2023-11-06 14:23

import backEnd.react_front_end.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(default='', max_length=400, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile-picture')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[backEnd.react_front_end.models.phone_regex_validator])),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=7)),
            ],
        ),
    ]
