# Generated by Django 4.2.5 on 2023-11-07 14:11

import backEnd.react_front_end.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(default='', max_length=400, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile-picture')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[backEnd.react_front_end.models.phone_regex_validator])),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookReadingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=60)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book-cover')),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Currently Reading', 'Currently Reading'), ('Finished', 'Finished')], max_length=30, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='react_front_end.profile')),
            ],
        ),
    ]
