# Generated by Django 4.2.5 on 2023-10-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_front_end', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(default='', max_length=400, primary_key=True, serialize=False),
        ),
    ]
