# Generated by Django 4.2.5 on 2023-11-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_front_end', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreadinglist',
            name='status',
            field=models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Want to read', 'Want to read'), ('Finished', 'Finished')], max_length=30, null=True),
        ),
    ]
