# Generated by Django 4.2.5 on 2023-11-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_front_end', '0002_alter_bookreadinglist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreadinglist',
            name='cover',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
