# Generated by Django 4.2.5 on 2023-11-16 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('react_front_end', '0003_alter_bookreadinglist_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=1200, null=True)),
                ('price', models.PositiveIntegerField()),
                ('cover', models.URLField(max_length=500)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='react_front_end.profile')),
            ],
        ),
    ]
