# Generated by Django 4.2.5 on 2023-11-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('react_front_end', '0004_bookstore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookstore',
            old_name='book_title',
            new_name='title',
        ),
    ]
