# Generated by Django 4.2.5 on 2023-12-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_front_end', '0005_rename_book_title_bookstore_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
