# Generated by Django 4.2.5 on 2023-12-01 15:25

import backEnd.react_front_end.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_front_end', '0006_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='price',
            field=models.FloatField(validators=[backEnd.react_front_end.models.validate_positive_float]),
        ),
    ]
