# Generated by Django 4.2.5 on 2023-12-01 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('react_front_end', '0007_alter_bookstore_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStoreLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='react_front_end.bookstore')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='react_front_end.profile')),
            ],
        ),
    ]
