# Generated by Django 4.2.5 on 2023-12-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_front_end', '0008_bookstorelikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='likes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
