# Generated by Django 4.2.5 on 2023-12-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_front_end', '0009_bookstore_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
