# Generated by Django 4.2.5 on 2023-12-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react_front_end', '0010_alter_bookstore_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='cover',
            field=models.URLField(max_length=1200),
        ),
    ]
